name: PR Guard

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Extract PR description
      id: pr_description
      run: echo "PR_DESCRIPTION=$(jq -r .pull_request.body $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}

    - name: Run script to post comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO_NAME: ${{ github.repository }}
        PR_DESCRIPTION: ${{ env.PR_DESCRIPTION }}
      run: python .github/scripts/pull-request-guard.py
    